branch-defaults:
  master:
    environment: node-express-env
    group_suffix: null
global:
  application_name: personal-website-2.0
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
